# Generated by Django 3.0.5 on 2021-04-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210425_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
