# Generated by Django 3.0.5 on 2021-04-29 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_auto_20210429_1034'),
        ('reviews', '0002_auto_20210429_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='titles.Title'),
            preserve_default=False,
        ),
    ]
